## 预备知识
本部分主要介绍一些基本技能，包括数据操作、数据预处理、线性代数、微积分、自动微分、概率等基础内容

### 数据操作
#### 关于张量

In [2]:
# 导入pytorch库
import torch

张量时一个拥有多个维度的数组，具有一个维度的张量对应数学中的向量，具有两个维度的张量对应数学中的矩阵
使用arange可以创建一个行向量

In [4]:
# 创建一个行向量，元素从0开始，步长为1，长度为12
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

通过shape属性可以得到张量的形状

In [5]:
x.shape

torch.Size([12])

通过numel()方法可以得到张量中元素的数量

In [10]:
x.numel()

12

通过reshape()方法可以改变张量的形状

In [15]:
X = x.reshape(3,4)
print(X)
X.shape

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


torch.Size([3, 4])

对于使用reshape()方法修改张量形状，不需要手动指定每个维度的大小
例如对于需要一个二维张量，指定其中一个维度大小，另一个维度写入-1，pytorch会自动计算另一个维度的大小

In [16]:
Y = x.reshape(2, -1)
print(Y)
Y.shape

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])


torch.Size([2, 6])

通过下面的方法可以分别创建一个指定形状的全0、全1、符合某个特定概率分布的张量

In [ ]:
# 创建一个指定形状的全0张量
x = torch.zeros(2, 3, 4)
x = torch.zeros((2,3,4))
# 上面两个方法都是可行的，第一种方式分别指定每个维度的大小，第二种方式传入了一个shape元组

# 创建一个指定形状的全1张量
x = torch.ones(2, 3, 4)

# 创建一个服从标准高斯分布的随机采样张量
x = torch.randn(3, 4)

tensor([[ 1.1405,  0.2631,  0.0361,  0.0171],
        [-1.2765, -0.1462,  1.0328,  2.2940],
        [-0.2439, -0.4963, -0.7998, -0.0844]])

通过下面的方式可以创建一个有确定赋值的张量

In [23]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

#### 运算符