## 预备知识
本部分主要介绍一些基本技能，包括数据操作、数据预处理、线性代数、微积分、自动微分、概率等基础内容

### 数据操作
#### 关于张量

In [44]:
# 导入pytorch库
import torch

张量时一个拥有多个维度的数组，具有一个维度的张量对应数学中的向量，具有两个维度的张量对应数学中的矩阵
使用arange可以创建一个行向量

In [45]:
# 创建一个行向量，元素从0开始，步长为1，长度为12
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

通过shape属性可以得到张量的形状

In [46]:
x.shape

torch.Size([12])

通过numel()方法可以得到张量中元素的数量

In [47]:
x.numel()

12

通过reshape()方法可以改变张量的形状

In [48]:
X = x.reshape(3,4)
print(X)
X.shape

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


torch.Size([3, 4])

对于使用reshape()方法修改张量形状，不需要手动指定每个维度的大小
例如对于需要一个二维张量，指定其中一个维度大小，另一个维度写入-1，pytorch会自动计算另一个维度的大小

In [49]:
Y = x.reshape(2, -1)
print(Y)
Y.shape

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])


torch.Size([2, 6])

通过下面的方法可以分别创建一个指定形状的全0、全1、符合某个特定概率分布的张量

In [50]:
# 创建一个指定形状的全0张量
x = torch.zeros(2, 3, 4)
x = torch.zeros((2,3,4))
# 上面两个方法都是可行的，第一种方式分别指定每个维度的大小，第二种方式传入了一个shape元组

# 创建一个指定形状的全1张量
x = torch.ones(2, 3, 4)
# 创建一个服从标准高斯分布的随机采样张量
x = torch.randn(3, 4)

# 创建一个和指定张量形状相同的全0张量
x = torch.zeros_like(x)
# 创建一个和指定张量形状相同的全1张量
x = torch.ones_like(x)
# 创建一个和指定张量形状相同的服从标准高斯分布的随机采样张量
x = torch.rand_like(x)

通过下面的方式可以创建一个有确定赋值的张量

In [51]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

通过arange()方法可以创建一个确定步长的一维张量

In [52]:
# 起始值：3，终止值(不包括)：15，步长：0.5
x = torch.arange(3, 15, 0.5)
x

tensor([ 3.0000,  3.5000,  4.0000,  4.5000,  5.0000,  5.5000,  6.0000,  6.5000,
         7.0000,  7.5000,  8.0000,  8.5000,  9.0000,  9.5000, 10.0000, 10.5000,
        11.0000, 11.5000, 12.0000, 12.5000, 13.0000, 13.5000, 14.0000, 14.5000])

#### 运算符
torch张量支持逐元素计算和矩阵运算两种方式，如下：

In [53]:
# 逐元素计算
x = torch.tensor([1, 2, 3, 4])
y = torch.tensor([5, 6, 7, 8])
z = x + y # 加
print(z)
z = x - y     # 减
print(z)
z = x * y     # 乘
print(z)
z = x / y     # 除
print(z)
z = x // y    # 整除，向下取整
print(z)
z = x ** y    # 幂
print(z)
z = x % y     # 取模
# 逐元素计算方法
z = torch.exp(x) # 取自然指数
print(z)

# 矩阵运算
x = torch.arange(12).reshape(4, 3)
print(x)
y = torch.tensor([[2, 0, 4, 3], [1, 5, 6, 1], [1, 0, 0, 5]]) 
z = x @ y # 矩阵乘法
print(z)
# 矩阵转置
z = x.T
print(z)
z = x.t() # 相比于T，t()方法会返回一个新张量，而T会返回一个视图，直接修改T返回的张量会修改原张量，而直接修改t()返回的张量不会修改原张量(参见后面原地操作部分)

# sum()方法可以对张量元素求和，返回一个单元素张量
z.sum()

tensor([ 6,  8, 10, 12])
tensor([-4, -4, -4, -4])
tensor([ 5, 12, 21, 32])
tensor([0.2000, 0.3333, 0.4286, 0.5000])
tensor([0, 0, 0, 0])
tensor([    1,    64,  2187, 65536])
tensor([ 2.7183,  7.3891, 20.0855, 54.5981])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
tensor([[ 3,  5,  6, 11],
        [15, 20, 36, 38],
        [27, 35, 66, 65],
        [39, 50, 96, 92]])
tensor([[ 0,  3,  6,  9],
        [ 1,  4,  7, 10],
        [ 2,  5,  8, 11]])


tensor(66)

通过cat方法，可以把多个张量在一个指定维度拼接(concatenate)在一起

In [54]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
y = torch.tensor([[7, 8, 9], [10, 11, 12]])
print(torch.cat((x, y), dim=0))
print(torch.cat((x, y), dim=1))

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])
tensor([[ 1,  2,  3,  7,  8,  9],
        [ 4,  5,  6, 10, 11, 12]])


#### 广播
广播机制允许我们进行不同形状张量的运算

In [55]:
a = torch.arange(3).reshape(3, 1)
b = torch.arange(2).reshape(1, 2)
print(a)
print(b)
print(a + b)
# 通过广播机制，张量通过复制元素的方式，使得两个张量形状一致，从而可以进行运算

tensor([[0],
        [1],
        [2]])
tensor([[0, 1]])
tensor([[0, 1],
        [1, 2],
        [2, 3]])


#### 索引和切片

In [56]:
x = torch.arange(20).reshape(4, 5)
print(x)
# 使用[-1]访问最后一个元素
print(x[0, -1])
# 使用[a:b]访问张量中第a个到第b(不包含)个元素的切片
print(x[1, 1:3])
# 使用[a:b:c]访问张量中第a个到第b(不包含)个元素，步长为c的切片
print(x[1, 1:4:2])
# 使用[:]访问所有元素
print(x[:, 1])


tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])
tensor(4)
tensor([6, 7])
tensor([6, 8])
tensor([ 1,  6, 11, 16])


#### 原地操作
对于一些操作，如x = x + y，一般来说，七过程为，开辟一块内存存储计算x + y得到的值，然后把x指向该值，在大量计算时，就涉及了频繁内存分配，对此，使用id()函数可以验证该情况，id()函数提供了内存中引用对象的确切地址。

In [57]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])
before = id(x)
x = x + y
after = id(x)
print(before == after)

False



通过一些简单的操作，可以在原始内存上进行修改，以避免该问题。
pytorch专门为这些操作提供了后缀为_的方法，如add_() sub_()等，这些方法会直接在原始内存上进行修改，而不会开辟新的内存空间。

In [58]:
x = torch.tensor([1, 2, 3], dtype=torch.float32)
y = torch.tensor([4, 5, 6], dtype=torch.float32)

x.add_(y)     # 元素加
print(x)
x.sub_(y)     # 元素减
print(x)
x.mul_(y)     # 元素乘
print(x)
x.div_(y)     # 元素除
print(x)
x.floor_divide_(y) # 元素向下整除
print(x)
x.remainder_(y) # 元素取模
print(x)
x.pow_(y) # 元素幂
print(x)
x.relu_() # 元素relu激活
print(x)
x.sigmoid_() # 元素sigmoid激活
print(x)
x.tanh_() # 元素tanh激活
print(x)
x.clamp_(1, 2) # 元素取值范围限制(min, max)
print(x)
x.copy_(y) # 复制
print(x)

tensor([5., 7., 9.])
tensor([1., 2., 3.])
tensor([ 4., 10., 18.])
tensor([1., 2., 3.])
tensor([0., 0., 0.])
tensor([0., 0., 0.])
tensor([0., 0., 0.])
tensor([0., 0., 0.])
tensor([0.5000, 0.5000, 0.5000])
tensor([0.4621, 0.4621, 0.4621])
tensor([1., 1., 1.])
tensor([4., 5., 6.])


这些操作中部分对应的自运算操作符也是原地操作，如下：

In [59]:
x += y
print(x)
x -= y
print(x)
x *= y
print(x)
x /= y
print(x)
x //= y
print(x)
x %= y
print(x)
x **= y
print(x)

tensor([ 8., 10., 12.])
tensor([4., 5., 6.])
tensor([16., 25., 36.])
tensor([4., 5., 6.])
tensor([1., 1., 1.])
tensor([1., 1., 1.])
tensor([1., 1., 1.])


切片操作是一种创建视图的操作，而不是创建新的张量，因此，切片操作不会开辟新的内存空间，利用这一特点也可以减少内存开销：

In [60]:
before = id(x)
x[:] = x + y
print(id(x))
print(before == id(x))

1666080316448
True


上述操作先创建了一个临时张量保存x + y的结果，然后回头赋值给x。
值得注意的是，由于切片操作的这种特性，在使用切片的时候需要注意一些问题防止错误修改了原本张量，例如：

In [61]:
print(x)
y = x[:]
y.add_(x)
print(x)
y.add(x)
print(x)

tensor([5., 6., 7.])
tensor([10., 12., 14.])
tensor([10., 12., 14.])


上面的示例中，张量y通过切片操作创建了一个x的视图，此时，使用原地操作修改y，实际上x的值也被修改了，
而使用非原地操作修改y，x的值并没有被修改，因此，在使用切片操作时，需要格外小心，避免错误修改了原本张量。这点对于 += -= 等原地操作符号同样适用。
矩阵的转置中，直接使用属性x.T会返回一个视图，修改该视图也会修改原张量

In [69]:
print(x)
y = x.T
y[0] = 100
print(x)

tensor([101.,  13.,  15.])
tensor([100.,  13.,  15.])


#### 把张量转换为其他类型python对象
转换为numpy数组(ndarry)

In [62]:
a = x.numpy()           # 底层共享内存(数据缓冲区)
b = torch.from_numpy(a) # 底层共享内存(数据缓冲区)
a[0] = 100              # 拷贝一份新数据，不共享内存
print(x)
print(b)
c = torch.tensor(a)
print(x)
print(a)
print(b)
print(c)
x += 1
print(a)
print(b)
print(c)

tensor([100.,  12.,  14.])
tensor([100.,  12.,  14.])
tensor([100.,  12.,  14.])
[100.  12.  14.]
tensor([100.,  12.,  14.])
tensor([100.,  12.,  14.])
[101.  13.  15.]
tensor([101.,  13.,  15.])
tensor([100.,  12.,  14.])


对于大小为1的张量，可以转换为python标量：

In [63]:
a = torch.tensor([1.5])
a, a.item(), float(a), int(a)

(tensor([1.5000]), 1.5, 1.5, 1)

### 数据预处理
#### 读取数据集
首先创建`../data/house_tiny.csv`文件，写入数据以创建一个简单人工数据集

In [64]:
import os
os.makedirs('../../data', exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
  f.write('NumRooms,Alley,Price\n') # 列名
  f.write('NA,Pave,127500\n') # 每行表示一个数据样本
  f.write('2,NA,106000\n')
  f.write('4,NA,178100\n')
  f.write('NA,NA,140000\n')

采用pandas包中的read_csv函数读取数据集

In [65]:
import pandas as pd
data = pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


#### 处理缺失值
数据中NaN表示缺失值，一般可以通过插值法或者删除法处理，插值法通过特定插值方式处理，删除法直接忽略对应数据
这里使用插值法处理

In [66]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = pd.get_dummies(inputs, dummy_na=True)
inputs = inputs.fillna(inputs.mean())
print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0       3.0        True      False
1       2.0       False       True
2       4.0       False       True
3       3.0       False       True


#### 转换为张量
在上述处理后，所有数据都转换为数值类型了(其中部分布尔类型也可以作为数字形式正常计算)
通过转换成张量形式可以方便后续操作

In [67]:
X = torch.tensor(inputs.to_numpy(dtype=float))
Y = torch.tensor(outputs.to_numpy(dtype=float))
print(X)
print(Y)

tensor([[3., 1., 0.],
        [2., 0., 1.],
        [4., 0., 1.],
        [3., 0., 1.]], dtype=torch.float64)
tensor([127500., 106000., 178100., 140000.], dtype=torch.float64)
